version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./audio_output:/app/audio_output
      - ./vector_storage:/app/vector_storage
      - ./model_cache:/app/model_cache
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 